[font]
size = 19.0

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.bold_italic]
family = "0xProto Nerd Font"
style = "Bold Italic"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
vi_mode_style.shape = "Underline"
vi_mode_style.blinking = "Always"
blink_interval = 500
